### PR TITLE
Add Required Labels Action

### PR DESCRIPTION
**Pull request by wpniederer**

### CODE REVIEW

**Comment by wpniederer** [comment]
@Mergifyio queue

**Comment by wpniederer** [comment]
@Mergifyio rebase

**Review by cti-harness — APPROVED** [review]

**Comment by wpniederer** [comment]
@Mergifyio refresh

**Comment by wpniederer** [comment]
@Mergifyio queue

**Review by cti-harness — APPROVED** [review]

**Comment by wpniederer** [comment]
@Mergifyio refresh

**Comment by wpniederer** [comment]
@Mergifyio refresh

**Comment by wpniederer** [comment]
@Mergifyio update

**Comment by wpniederer** [comment]
@Mergifyio refresh

**Pull request merged**
